### ISSUE TITLE
Add User

### ISSUE THREAD

**Issue by clangelov** [Sports-Goods-B2B/SportsGoods#1]
The only users which we will have in the applications will be the sports goods administrators.
They should be able to log in and log out of the MVC application. 

Create db named SportsGoods use code-first approach 

We can use the build in user from APS.NET  
Seed at least 3 admins for the app

the project skeleton should have the bare minimum of dependencies like Mediatr and EnitiyFramework Core 

Make sure you add a good documentation how to start the app

**Comment by LVarsaminov** [comment]
DONE : 

Moved DBContext to SportsGoods.Data
Moved Administrator to SportsGoods.Data
Created Interface for DBContext class
Had a problem with con string and got it fixed, now DB is connected without any issues.
Made references amongst the projects in the solution.
Created graph with project references.
Created Administrator table in the Database that uses the IdentityUser class so it has the features asp.net core offers
Successfully seeded 3 admin records, but for some reason they are not added in the order i created them
