### ISSUE TITLE
[Core][Data][App] Update Product 

### ISSUE THREAD

**Issue by clangelov** [Sports-Goods-B2B/SportsGoods#10]
Product Brand should not be a string, but an actual Brand object.
  
One Product can have one Brand 
And One Brand can have many Products

We are going to keep the existing xml file to build data 

If data generation needs to be performed in a certain order you can take advantage of a design pattern.

**Comment by LVarsaminov** [comment]
Plan:
1. Change Brand string property to Brand object.
2. Refactor all the code where we set a value to the Brand property.
3.Add Media.cs and change the picture property to Media
3.Add migration and update the database.
4.Create BrandService.cs and think of a way to extract the logic of the ProductService.cs
5.Implement order of execution between the services.
